name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:  # Manual trigger for testing

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Debugging step to check the GitHub user's contribution data
      - name: Test API Call to fetch user events
        run: |
          echo "Fetching user events..."
          curl -s https://api.github.com/users/rishifx/events | jq .  # Replace with your GitHub username

      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: rishifx  # Replace with your GitHub username

      - name: Push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "Update snake animation"
          git push origin output  # Replace 'output' with your branch name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
