name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: rishifx
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          github_token: ${{ secrets.GITHUB_TOKEN }}
